pipeline:
  update_pr:
    image: plugins/git
    commands:
    - export BRANCH_SRC=origin/${DRONE_COMMIT_REFSPEC%%:*} BRANCH_DST=origin/${DRONE_BRANCH}
    - cp -rpf .git .git.bak
    - git fetch && git checkout $BRANCH_SRC && git merge $BRANCH_SRC
    - rm -rf .git && mv -f .git.bak .git
    when:
      event: pull_request
      branch: [ master, release* ]
  test:
    image: node:9.9
    environment:
      - RUN_MODE=k8s
    commands:
      - rm -f yarn.lock || true
      - . ./.env.test
      - yarn -s --no-progress --non-interactive --production=false
      - yarn updateSchema
      - yarn relay
      - yarn ci
    when:
      event: pull_request
      branch: [ master, release* ]
  build4nightly:
    image: node:9.9
    commands:
      - . ./.env.nightly
      - rm -f yarn.lock || true
      - yarn -s --no-progress --non-interactive --production=false
      - yarn updateSchema
      - yarn relay
      - yarn build
      - yarn server:dist:build
    when:
      event: push
      branch: master
  node_package4nightly:
    image: plugins/docker
    repo: storiqateam/stq-node
    environment:
      - TIER=nightly
    tags:
      - nightly_${DRONE_BRANCH/\//_}
      - nightly_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.node
    when:
      event: [ push, tag ]
      branch: master
  static_package4nightly:
    image: plugins/docker
    repo: storiqateam/stq-static
    tags:
      - nightly_${DRONE_BRANCH/\//_}
      - nightly_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.static
    when:
      event: [ push, tag ]
      branch: master
  deploy2nightly:
    image: jackthestripper/drone_k8s_rollout:20180510
    user: admin
    token: 32txou6YhrlD3sHcpxsiCmP1m7taE1fY
    addr: https://api.nightly.stq.cloud
    object: front
    kind: deployment
    namespace: default
    img_names:
      - storiqateam/stq-node
      - storiqateam/stq-static
    img_cnts:
      - node
      - static
    img_tags:
      - nightly_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
      - nightly_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    ca: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRlNTbzZ4bytxYmxYWFVweU1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UZ3dOREV3TVRBeE9ESXhXaGNOTWpnd05EQTVNVEF4T0RJeApXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXdDZlhvZmIwMHQ2ZG9xMm1MZzlreUxjTE5lTEYzVlM0R29lRUNOMCtuaityall1THRaYlkKOStiV0JBMW1Ua3NWS3JGcUFob2l5K1g0dkRzYWcyWmExMm80cVlRci9FWGs2cVRtRnluT0s1NkpLdWJoVXNoRAp3QjQxTDgvaXJ1NmdNUWs2a2lYbnVuN2UzS25iemJlZml5QytVc2I5TFR4UWRPMldvTm5tQVpZV2g3QjR4YUJmCm5vSGRHZE4wQTBwZlNBZU1SYWZjb0M3QmNyQldiQlUzMG4xMlM3bFdUTkl0OU82SWMwVUt2NzFXTFlDeFNOQm8KSGhkaEZzZzlaWjQ4dVBPQkRzRlBxUXFsTUdtWEtUVW1ydS8zTG1qSnRFV1h5WVJ0QjJvOVlreGdTUUV4Yi9FZwpIdjNGQ1dYblY2NVNDUTRnQTZHL2tINUV4N1hoMnlybGh3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFjWkVIMEc4enFmU2QKR1Q5RDMraVVDdnl5akxrY2xLUjhRWENEVGdxVXB3TGNaN0FuUU1uN2xkalk0UjJHR3lnMnZteWkyZ1AzbktxRQpPWldGTk5WYjUxOHkyN3c2bXdTUnVuUHZ1VzdzT0NFS2I3MmhzN1dFZUNVUGZ3Ni9kVUFueDNzVW1CV243RzVTCjhBRjBvc0lQZVNzeXhVZnNpc25ucG43MGVuRHdtV3k3SzdhYXJvb3hFNk0zMDhNWFROeGh0bW9SOVFPQzR3QUgKWk80SzM0eFpLK2xoTHZNcFpZSHVyeEZUZFJiR3JhTHNKVjZ6YlRHdURlSTAwckY3MVdhMHJlUkF0NVZ6TEgyNwppclJMUlRZVFphQmpuTHlrcGVYbGw3eEFnamxpWVM1L3B1RHZsMFk0elBxMFI4U3NjYXRtUTB0SnVIa2tQaElkCktXalVlMjM2TFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    when:
      branch: master
      event: push
  build4stable:
    image: node:9.9
    commands:
      - . ./.env.stable
      - rm -f yarn.lock || true
      - yarn -s --no-progress --non-interactive --production=false
      - yarn updateSchema
      - yarn relay
      - yarn build
      - yarn server:dist:build
    when:
      event: push
      branch: master
  node_package4stable:
    image: plugins/docker
    repo: storiqateam/stq-node
    environment:
      - TIER=stable
    tags:
      - stable_${DRONE_BRANCH/\//_}
      - stable_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.node
    when:
      event: [ push, tag ]
      branch: master
  static_package4stable:
    image: plugins/docker
    repo: storiqateam/stq-static
    tags:
      - stable_${DRONE_BRANCH/\//_}
      - stable_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.static
    when:
      event: [ push, tag ]
      branch: master
  deploy2stable:
    image: jackthestripper/drone_k8s_rollout:20180510
    user: admin
    token: vhkzUYmnPSI7MtJO3Et9KczuGoS0goqV
    addr: https://api.stable.stq.cloud
    object: front
    kind: deployment
    namespace: default
    img_names:
      - storiqateam/stq-node
      - storiqateam/stq-static
    img_cnts:
      - node
      - static
    img_tags:
      - stable_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
      - stable_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    ca: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRlNaRkNyd2ttZEZsRmNURk1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UZ3dOREUxTVRZeE1ETTJXaGNOTWpnd05ERTBNVFl4TURNMgpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTNvSk03QkI3dUF6WUFqQ1FUM3VyeWg1NW40ck5GcjdWUWFzRUhLdkMvVjgzbkVkeTJYLzcKbHlqamlYTEJVKzkvdDV5eUpCUG1VMDVmSHNNblBTTnl1bUh6M2Nmd1U4NnliVTVuUlFjOXRLTkE0UFJ1dW80cgpwMUJlUzNyZ1FoTDN6d3JBTVNYc2toZHRKZms4SjZJR3cvU3Z4Q051RStRNi8zb0JVS1RkU3QyUEZKOVpuUit0Cjl5ZitLa0VLZE1SY1RGRGplbUJCSTlhM1k0amxZQXNjd3hnbStzckpxQjYyaG8zQ1VMT0pBMEZmMEsxSnprNHQKKzRuWnBNSU1zamRKQS9mc1B6Qi9IMXpUeTdZK1pJbzJJTWVGdjg1djk1VEg3TU41YnZ2aWk1bGxyanFOQit4cgpBSXlxSHc0bWxGenlKUzBaUUNEcWhhNmYzdTRzMGIwdFN3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFVUWxKSWUrVWxDZ1kKbG0vd1ppYk9xdXJkUUFBT2dpSUpLdjIzbm1CUWc4MDJjM1pUdFFTZnBDTWRxTVRwRVR5SjIyTlN5elRiZUlGcgpjTEJuVCs0b2dDcUdnMm9nTHRZaDM2aVA0aFIyeXlkU094aFdRZlVCaEo5KzlxZW1iZFVOWU90SGZmakl1bE9TCko3aHY4eTFlWXN1U2Exdjl5TDNIckw2ODVVenVKR2ZyRmllMFovRUZWNlMwS1VkMFJEa3J1WnhPWVp2V01vYmoKVUZPMERyaTFFc2xMSnJXVHQzVFIwQXpZWWhjLzZJQk9NRnBDQ3hmaVFLSERFWjBSWCtCVHlGVVZtV29MYkJuRgozRGFtOFNId21PbkExbVZrR0ZVS3hwWWJ4aUgweDdQK3Ntb1lKbm82Q1NYVmpXOVI1V1NTWWFkQi9PbnBTYkoxClppU2JqVEVmMVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    when:
      branch: master
      event: push
  build4stage:
    image: node:9.9
    commands:
      - . ./.env.stage
      - rm -f yarn.lock || true
      - yarn -s --no-progress --non-interactive --production=false
      - yarn updateSchema
      - yarn relay
      - yarn build
      - yarn server:dist:build
    when:
      event: push
      branch: release*
  node_package4stage:
    image: plugins/docker
    repo: storiqateam/stq-node
    environment:
      - TIER=stage
    tags:
      - stage_${DRONE_BRANCH/\//_}
      - stage_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.node
    when:
      event: [ push, tag ]
      branch: release*
  static_package4stage:
    image: plugins/docker
    repo: storiqateam/stq-static
    tags:
      - stage_${DRONE_BRANCH/\//_}
      - stage_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.static
    when:
      event: [ push, tag ]
      branch: release*
  deploy2stage:
    image: jackthestripper/drone_k8s_rollout:20180510
    user: admin
    token: PW2clI0vKqLi3eywlN776rMyE7hk1pgX
    addr: https://api.stage.stq.cloud
    object: front
    kind: deployment
    namespace: default
    img_names:
      - storiqateam/stq-node
      - storiqateam/stq-static
    img_cnts:
      - node
      - static
    img_tags:
      - stage_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
      - stage_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    ca: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRlNKQTd5MHlUTHRrNWtXak1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UZ3dOREF5TVRReE1ESXdXaGNOTWpnd05EQXhNVFF4TURJdwpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXg3bHI5ejdaSmF3ZXNnUCt6SW1hY0ZCYVdZNS8rSUlEa2xVcDNCN29VUUdCclM2bkEwbDIKYVU0STc4WlpZQThwcEplOVhFL2daVUVNWEdFdlZuWUozL1pybVBqSWMybnF6T3gxc2N6WmlDamllWG1nakVHKwpvalpoc2tGc3d3R01sRnFsODVtK05UVWdEYUYwSjQ1NkFrM3hoUkdWT1BYaDNMWnN4cXZNcENmNmFrYkNjMTJCCnVjak5uUThmZVc5Sjc4VzkwWGJuSG5kY1c4cWUwQ1dLWnBZSkdlQkd6SHJjczFGc09leURSOHhqVW5pejkzSE8KZ0poTXF4VmYzTk5rL3lYSzZnS1FHVHBGY05uUXlLRy9MZ3JGWW10aGs1UWFORUZLV3hiK0RDVnJsa0F3VmhJRQpxT1FYRWlmQjB5WXpCdmp1Tmxib1JSVlpMeDRwRTNsOFZ3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGZmpyVnUyYmpobGgKZXhiOUo5WFFEaWl1WngwVGZBRDZsRjRBb3RhdFV3UjNMNVdUSlFYMHJvZWNLMHNjWHBiUUx6ME5vTThLbmtPUApyVkk4UWdKY1l1bHJSRmlqWmxrMElQNUJRb3ZVM1RnSlB5RG5xS0xCaTdtR2ZyUXB2YzVrVHVBOTJTb3FGT2pqCjNtZEdqNFprVmh1QkhYWXNOUk53VEFtUVB5WXozZXJFVkM5MDhqalhRYTB1cnQvZWFEd1ZNMFAxanhZZklrUDAKYm9aVmRPWWR6MzJjME5YRXRPZDMvWC9vaWdSSmhSMG5Sc2ZVbDRpd1BBb1JBNlhmM2tpWUNoWWdLci9IZzBudAp2azJ5Yjc0c0ZpZ0tyalZ4cTZNeHRkdGlBUWwrU0g0TkU5RmhYT3FaSFFSVTB4dk9YRC9WaU1qaVl2NXVVc0NrClhza0ZxSyt2eVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    when:
      branch: release*
      event: push
  notify_slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: release
    icon_url: https://drone.io/favicon.ico
    username: cd.stq.cloud
    template: >
      {{#success build.status}}
        Build {{build.number}} for {{repo.name}} branch {{build.branch}} succeeded.
      {{else}}
        Build {{build.number}} for {{repo.name}} branch {{build.branch}} failed.
      {{/success}}
    when:
      event: push
      branch: [ master, release ]
      status: [ failure, success ]
