pipeline:
  test:
    image: node:9.9-slim
    environment:
      - RUN_MODE=k8s
    commands:
      - yarn test
      - yarn ci
    when:
      event: pull_request
  build4nightly:
    image: node:9.9-slim
    commands:
      - . .env.nightly
      - apt-get update
      - apt-get install -y git
      - rm -f /app/yarn.lock || true
      - yarn -s --no-progress --non-interactive --production=false
      - yarn updateSchema
      - yarn relay
    when:
      event: push
      branch: feature/cd
  node_package4nightly:
    image: plugins/docker
    repo: storiqateam/stq-node
    environment:
      - TIER=nightly
    tags:
      - nightly_${DRONE_BRANCH/\//_}
      - nightly_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.node
    when:
      event: [ push, tag ]
      branch: feature/cd
  static_package4nightly:
    image: plugins/docker
    repo: storiqateam/stq-static
    tags:
      - nightly_${DRONE_BRANCH/\//_}
      - nightly_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"
    dockerfile: docker/Dockerfile.static
    when:
      event: [ push, tag ]
      branch: feature/cd
  deploy2nightly:
    image: jackthestripper/drone_k8s_rollout
    user: admin
    token: 32txou6YhrlD3sHcpxsiCmP1m7taE1fY
    addr: https://api.nightly.stq.cloud
    object: stores
    kind: deployment
    imgs: [ storiqateam/stq-node, storiqateam/stq-static ]
    cnts: [ node, static ]
    tags:
      - nightly_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
      - nightly_${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    ca: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRlNTbzZ4bytxYmxYWFVweU1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UZ3dOREV3TVRBeE9ESXhXaGNOTWpnd05EQTVNVEF4T0RJeApXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXdDZlhvZmIwMHQ2ZG9xMm1MZzlreUxjTE5lTEYzVlM0R29lRUNOMCtuaityall1THRaYlkKOStiV0JBMW1Ua3NWS3JGcUFob2l5K1g0dkRzYWcyWmExMm80cVlRci9FWGs2cVRtRnluT0s1NkpLdWJoVXNoRAp3QjQxTDgvaXJ1NmdNUWs2a2lYbnVuN2UzS25iemJlZml5QytVc2I5TFR4UWRPMldvTm5tQVpZV2g3QjR4YUJmCm5vSGRHZE4wQTBwZlNBZU1SYWZjb0M3QmNyQldiQlUzMG4xMlM3bFdUTkl0OU82SWMwVUt2NzFXTFlDeFNOQm8KSGhkaEZzZzlaWjQ4dVBPQkRzRlBxUXFsTUdtWEtUVW1ydS8zTG1qSnRFV1h5WVJ0QjJvOVlreGdTUUV4Yi9FZwpIdjNGQ1dYblY2NVNDUTRnQTZHL2tINUV4N1hoMnlybGh3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFjWkVIMEc4enFmU2QKR1Q5RDMraVVDdnl5akxrY2xLUjhRWENEVGdxVXB3TGNaN0FuUU1uN2xkalk0UjJHR3lnMnZteWkyZ1AzbktxRQpPWldGTk5WYjUxOHkyN3c2bXdTUnVuUHZ1VzdzT0NFS2I3MmhzN1dFZUNVUGZ3Ni9kVUFueDNzVW1CV243RzVTCjhBRjBvc0lQZVNzeXhVZnNpc25ucG43MGVuRHdtV3k3SzdhYXJvb3hFNk0zMDhNWFROeGh0bW9SOVFPQzR3QUgKWk80SzM0eFpLK2xoTHZNcFpZSHVyeEZUZFJiR3JhTHNKVjZ6YlRHdURlSTAwckY3MVdhMHJlUkF0NVZ6TEgyNwppclJMUlRZVFphQmpuTHlrcGVYbGw3eEFnamxpWVM1L3B1RHZsMFk0elBxMFI4U3NjYXRtUTB0SnVIa2tQaElkCktXalVlMjM2TFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    when:
      branch: feature/cd
      event: push
  #build4stable:
    #image: node:9.9-slim
    #environment:
      #- TIER=stable
    #commands:
      #- apt-get update
      #- apt-get install -y git
      #- rm -f /app/yarn.lock || true
      #- . .env.${TIER}
      #- yarn -s --no-progress --non-interactive --production=false
      #- yarn updateSchema
      #- yarn relay
    #when:
      #event: push
      #branch: master
  #deploy2stage:
    #image: quay.io/honestbee/drone-kubernetes
    #kubernetes_server: https://api.stage.stq.cloud
    #kubernetes_token: PW2clI0vKqLi3eywlN776rMyE7hk1pgX
    #namespace: default
    #deployment: saga
    #repo: storiqateam/stq-saga
    #container: saga
    #tag: ${DRONE_BRANCH/\//_}${DRONE_BUILD_NUMBER}
    #when:
      #branch: release*
      #event: push
  notify_slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: release
    icon_url: https://drone.io/favicon.ico
    username: cd.stq.cloud
    template: >
      {{#success build.status}}
        Build {{build.number}} for {{repo.name}} branch {{build.branch}} succeeded.
      {{else}}
        Build {{build.number}} for {{repo.name}} branch {{build.branch}} failed.
      {{/success}}
    when:
      event: push
      branch: [ master, release ]
      status: [ failure, success ]
