pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    mount:
    - node_modules
    restore: true

###
# Test PR
###

  update_pr:
    image: plugins/git
    commands:
    - export BRANCH_SRC=origin/${DRONE_COMMIT_REFSPEC%%:*} BRANCH_DST=origin/${DRONE_BRANCH}
    - cp -rpf .git .git.bak
    - git config --global user.email "service@storiqa.com" && git config --global user.name "Storiqa Common"
    - git fetch && git checkout $BRANCH_SRC && git merge --no-commit $BRANCH_DST
    - rm -rf .git && mv -f .git.bak .git
    when:
      event: pull_request
  test:
    image: node:9.9
    environment:
    - RUN_MODE=k8s
    commands:
    - rm -f yarn.lock || true
    - . ./.env.test
    - yarn -s --no-progress --non-interactive --production=false
    - yarn updateSchema
    - yarn relay
    - yarn ci
    when:
      event: pull_request

###
# Build and deploy to nightly
###

  build4nightly:
    image: node:9.9
    commands:
    - . ./.env.nightly
    - rm -f yarn.lock || true
    - npm config delete _auth
    - yarn -s --no-progress --non-interactive --production=false
    - yarn updateSchema
    - yarn relay
    - yarn build
    - yarn server:dist:build
    when:
      event: push
      branch: master
  node_package4nightly:
    image: plugins/docker
    group: package
    repo: storiqateam/stq-node
    environment:
    - TIER=nightly
    tags:
    - nightly_${DRONE_BRANCH//\//_}
    - nightly_${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    dockerfile: docker/Dockerfile.node
    secrets:
    - docker_username
    - docker_password
    when:
      event: push
      branch: master
  static_package4nightly:
    image: plugins/docker
    group: package
    repo: storiqateam/stq-static
    tags:
    - nightly_${DRONE_BRANCH//\//_}
    - nightly_${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    dockerfile: docker/Dockerfile.static
    secrets:
    - docker_username
    - docker_password
    when:
      event: push
      branch: master
  deploy2nightly:
    image: jackthestripper/drone_setimage
    object: front
    kind: deployment
    namespace: default
    img_names:
    - storiqateam/stq-node
    - storiqateam/stq-static
    img_cnts:
    - node
    - static
    img_tags:
    - nightly_${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    - nightly_${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    secrets:
    - source: k8s_nightly_ca
      target: k8s_ca
    - source: k8s_nightly_user
      target: k8s_user
    - source: k8s_nightly_token
      target: k8s_token
    - source: k8s_nightly_addr
      target: k8s_addr
    when:
      branch: master
      event: push

###
# Build and deploy to stable
###

  build4stable:
    image: node:9.9
    commands:
    - . ./.env.stable
    - rm -f yarn.lock || true
    - npm config delete _auth
    - yarn -s --no-progress --non-interactive --production=false
    - yarn updateSchema
    - yarn relay
    - yarn build
    - yarn server:dist:build
    when:
      event: deployment
      environment: stable
  node_package4stable:
    image: plugins/docker
    group: package
    repo: storiqateam/stq-node
    environment:
    - TIER=stable
    tags:
    - stable_${DRONE_BRANCH//\//_}
    - stable_${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    dockerfile: docker/Dockerfile.node
    secrets:
    - docker_username
    - docker_password
    when:
      event: deployment
      environment: stable
  static_package4stable:
    image: plugins/docker
    group: package
    repo: storiqateam/stq-static
    tags:
    - stable_${DRONE_BRANCH//\//_}
    - stable_${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    dockerfile: docker/Dockerfile.static
    secrets:
    - docker_username
    - docker_password
    when:
      event: deployment
      environment: stable
  deploy2stable:
    image: jackthestripper/drone_setimage
    object: front
    kind: deployment
    namespace: default
    img_names:
    - storiqateam/stq-node
    - storiqateam/stq-static
    img_cnts:
    - node
    - static
    img_tags:
    - stable_${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    - stable_${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    secrets:
    - source: k8s_stable_ca
      target: k8s_ca
    - source: k8s_stable_user
      target: k8s_user
    - source: k8s_stable_token
      target: k8s_token
    - source: k8s_stable_addr
      target: k8s_addr
    when:
      branch: master
      event: deployment
      environment: stable

###
# Build and deploy to stage
###

  build4stage:
    image: node:9.9
    commands:
    - . ./.env.stage
    - rm -f yarn.lock || true
    - npm config delete _auth
    - yarn -s --no-progress --non-interactive --production=false
    - yarn updateSchema
    - yarn relay
    - yarn build
    - yarn server:dist:build
    when:
      event: tag
  node_package4stage:
    image: plugins/docker
    group: package
    repo: storiqateam/stq-node
    environment:
    - TIER=stage
    tags: 'stage_${DRONE_TAG}'
    dockerfile: docker/Dockerfile.node
    secrets:
    - docker_username
    - docker_password
    when:
      event: tag
  static_package4stage:
    image: plugins/docker
    group: package
    repo: storiqateam/stq-static
    tags: 'stage_${DRONE_TAG}'
    dockerfile: docker/Dockerfile.static
    secrets:
    - docker_username
    - docker_password
    when:
      event: tag
  deploy2stage:
    image: jackthestripper/drone_setimage
    object: front
    kind: deployment
    namespace: default
    img_names:
    - storiqateam/stq-node
    - storiqateam/stq-static
    img_cnts:
    - node
    - static
    img_tags:
    - 'stage_${DRONE_TAG}'
    - 'stage_${DRONE_TAG}'
    secrets:
    - source: k8s_stage_ca
      target: k8s_ca
    - source: k8s_stage_user
      target: k8s_user
    - source: k8s_stage_token
      target: k8s_token
    - source: k8s_stage_addr
      target: k8s_addr
    when:
      event: tag

###
# Build and deploy to production
###

  build4production:
    image: node:9.9
    commands:
    - . ./.env.production
    - rm -f yarn.lock || true
    - npm config delete _auth
    - yarn -s --no-progress --non-interactive --production=false
    - yarn updateSchema
    - yarn relay
    - yarn build
    - yarn server:dist:build
    when:
      event: deployment
      environment: production
  node_package4production:
    image: plugins/docker
    group: package
    repo: storiqateam/stq-node
    environment:
    - TIER=production
    tags: 'prod_${DRONE_TAG}'
    dockerfile: docker/Dockerfile.node
    secrets:
    - docker_username
    - docker_password
    when:
      event: deployment
      environment: production
  static_package4production:
    image: plugins/docker
    group: package
    repo: storiqateam/stq-static
    tags: 'prod_${DRONE_TAG}'
    dockerfile: docker/Dockerfile.static
    secrets:
    - docker_username
    - docker_password
    when:
      event: deployment
      environment: production
  deploy2production:
    image: jackthestripper/drone_setimage
    object: front
    kind: deployment
    namespace: default
    img_names:
    - storiqateam/stq-node
    - storiqateam/stq-static
    img_cnts:
    - node
    - static
    img_tags:
    - prod_${DRONE_TAG}
    - prod_${DRONE_TAG}
    secrets:
    - source: k8s_prod_ca
      target: k8s_ca
    - source: k8s_prod_user
      target: k8s_user
    - source: k8s_prod_token
      target: k8s_token
    - source: k8s_prod_addr
      target: k8s_addr
    when:
      event: deployment
      environment: production

###
# Notifications and post-deploy ops
###

  rebuild-cache:
    group: package
    image: plugins/s3-cache:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    mount:
    - node_modules
    rebuild: true
    when:
      branch: master
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: release
    icon_url: https://drone.io/favicon.ico
    username: cd.stq.cloud
    template: >
      {{#success build.status}}
        {{repo.name}} has been released to stage.stq.cloud!
      {{else}}
        Failed to deploy {{repo.name}} to stage.stq.cloud! More details here {{build.link}}
      {{/success}}
    when:
      event: tag
      status:
      - success
      - failure
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: release
    icon_url: https://drone.io/favicon.ico
    username: cd.stq.cloud
    template: >
      {{#success build.status}}
        {{repo.name}} has been released to production.stq.cloud!
      {{else}}
        Failed to deploy {{repo.name}} to production.stq.cloud! More details here {{build.link}}
      {{/success}}
    when:
      event: deployment
      environment: production
      status:
      - success
      - failure

