// flow-typed signature: 2ea404237bd6010eb94170dcf503d7c9
// flow-typed version: <<STUB>>/react-autosize-textarea_v^3.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-autosize-textarea'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-autosize-textarea' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-autosize-textarea/lib/index' {
  declare module.exports: any;
}

declare module 'react-autosize-textarea/lib/TextareaAutosize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-autosize-textarea/lib/index.js' {
  declare module.exports: $Exports<'react-autosize-textarea/lib/index'>;
}
declare module 'react-autosize-textarea/lib/TextareaAutosize.js' {
  declare module.exports: $Exports<'react-autosize-textarea/lib/TextareaAutosize'>;
}
