// flow-typed signature: 8988a7783d67606fc4bf59b5bfec9d38
// flow-typed version: <<STUB>>/universal-cookie_v^2.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-cookie/lib/Cookies' {
  declare module.exports: any;
}

declare module 'universal-cookie/lib/index' {
  declare module.exports: any;
}

declare module 'universal-cookie/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-cookie/lib/Cookies.js' {
  declare module.exports: $Exports<'universal-cookie/lib/Cookies'>;
}
declare module 'universal-cookie/lib/index.js' {
  declare module.exports: $Exports<'universal-cookie/lib/index'>;
}
declare module 'universal-cookie/lib/utils.js' {
  declare module.exports: $Exports<'universal-cookie/lib/utils'>;
}
