version: '3'
services:
  stq-front-js:
    image: "node:6"
    container_name: stq-front-js
    command: ["sh", "-c", "yarn ; yarn start"]
    working_dir: "/app"
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/app
    ports:
      - 3000:3000
