// flow-typed signature: 9eccc672955469b1d321b29c4575821c
// flow-typed version: <<STUB>>/@storiqa/shared_vgit+https://stqcommon:Tz-q6qDL%23d3Mz8hm@github.com/StoriqaTeam/libstqfrontend/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storiqa/shared'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storiqa/shared' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storiqa/shared/dist/index' {
  declare module.exports: any;
}

declare module '@storiqa/shared/dist/rules/notEmpty' {
  declare module.exports: any;
}

declare module '@storiqa/shared/dist/specs/index' {
  declare module.exports: any;
}

declare module '@storiqa/shared/dist/specs/profile' {
  declare module.exports: any;
}

declare module '@storiqa/shared/dist/utils/extractErrors' {
  declare module.exports: any;
}

declare module '@storiqa/shared/dist/utils/index' {
  declare module.exports: any;
}

declare module '@storiqa/shared/dist/utils/validate' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/index' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/index.test' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/rules/notEmpty' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/rules/notEmpty.test' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/specs/index' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/specs/profile' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/specs/profile.test' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/utils/extractErrors' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/utils/extractErrors.test' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/utils/index' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/utils/validate' {
  declare module.exports: any;
}

declare module '@storiqa/shared/src/utils/validate.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storiqa/shared/dist/index.js' {
  declare module.exports: $Exports<'@storiqa/shared/dist/index'>;
}
declare module '@storiqa/shared/dist/rules/notEmpty.js' {
  declare module.exports: $Exports<'@storiqa/shared/dist/rules/notEmpty'>;
}
declare module '@storiqa/shared/dist/specs/index.js' {
  declare module.exports: $Exports<'@storiqa/shared/dist/specs/index'>;
}
declare module '@storiqa/shared/dist/specs/profile.js' {
  declare module.exports: $Exports<'@storiqa/shared/dist/specs/profile'>;
}
declare module '@storiqa/shared/dist/utils/extractErrors.js' {
  declare module.exports: $Exports<'@storiqa/shared/dist/utils/extractErrors'>;
}
declare module '@storiqa/shared/dist/utils/index.js' {
  declare module.exports: $Exports<'@storiqa/shared/dist/utils/index'>;
}
declare module '@storiqa/shared/dist/utils/validate.js' {
  declare module.exports: $Exports<'@storiqa/shared/dist/utils/validate'>;
}
declare module '@storiqa/shared/src/index.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/index'>;
}
declare module '@storiqa/shared/src/index.test.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/index.test'>;
}
declare module '@storiqa/shared/src/rules/notEmpty.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/rules/notEmpty'>;
}
declare module '@storiqa/shared/src/rules/notEmpty.test.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/rules/notEmpty.test'>;
}
declare module '@storiqa/shared/src/specs/index.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/specs/index'>;
}
declare module '@storiqa/shared/src/specs/profile.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/specs/profile'>;
}
declare module '@storiqa/shared/src/specs/profile.test.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/specs/profile.test'>;
}
declare module '@storiqa/shared/src/utils/extractErrors.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/utils/extractErrors'>;
}
declare module '@storiqa/shared/src/utils/extractErrors.test.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/utils/extractErrors.test'>;
}
declare module '@storiqa/shared/src/utils/index.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/utils/index'>;
}
declare module '@storiqa/shared/src/utils/validate.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/utils/validate'>;
}
declare module '@storiqa/shared/src/utils/validate.test.js' {
  declare module.exports: $Exports<'@storiqa/shared/src/utils/validate.test'>;
}
